Auto Claim Stray Rabbits
odtheking/Odin pull request #80
Opened 2024-06-15 02:31 UTC by Triggered0

2024-06-20 17:59 UTC, freebonsai requested changes

2024-06-20 17:59 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/ChocolateFactory.kt
> +                for (slot in container.inventorySlots) {
use container.inventorySlots.find { // logic } instead

2024-07-05 21:23 UTC, Triggered0 commented
@freebonsai

2024-07-07 19:35 UTC, freebonsai approved these changes

2024-07-07 19:35 UTC, merged