add autoharp module
odtheking/Odin pull request #81
Opened 2024-06-17 14:28 UTC by x45k

its autoharp, self explanatory. its modified from floppa, but since cancelinteract.kt used floppa and modified it, i assume it is ok?

2024-06-20 15:42 UTC, freebonsai requested changes
Mostly looks fine, fix my comments and remove as much indentation as possible and i will merge.

2024-06-20 15:42 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +                mc.playerController.windowClick(
use PlayerUtils.windowclick (look at autoterms or something)

2024-06-20 15:42 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +    fun onRender(event: GuiScreenEvent.BackgroundDrawnEvent) {
Use a tickevent instead of a renderevent

2024-06-20 15:42 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +            val chestName = container.lowerChestInventory.displayName.unformattedText
use ContainerChest.name extension value from Utils.kt, container.name in this case

2024-06-21 16:34 UTC, x45k commented
should be done now

2024-07-07 19:40 UTC, freebonsai requested changes
not much to change, ping when done

2024-07-07 19:40 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +
remove extra space

2024-07-07 19:40 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +            val chestName = container.lowerChestInventory.displayName.unformattedText
do the same as you do later on in the code, container.name since its known its a ContainerChest

2024-07-07 19:40 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoHarp.kt
> +                windowClick(container.windowId, slot.slotNumber, 0, true) // Assuming left-click mode (0) and instant action (true)
PlayerUtils.windowClick(slot.slotNumber, PlayerUtils.ClickType.Left)

2024-07-09 14:50 UTC, merged