Implement auto i4
odtheking/Odin pull request #85
Opened 2024-07-10 17:30 UTC by viandoxdev

This PR implements auto i4, tested and works but not perfect yet (also code is not great, I've never really worked with Kotlin before).

TODO:
 - [ ] more testing, not sure if auto phoenix is consistent
 - [ ] make sure risky tag is on
 - [ ] Code cleanup ?

2024-07-17 15:18 UTC, freebonsai requested changes
Just small stuff, do you have a recent video of how it works with everything?
Tell me when you have fixed my comments and I will look over again and merge.

2024-07-17 15:18 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/utils/skyblock/ItemUtils.kt
> +        return this?.unformattedName?.noControlCodes?.equalsOneOf("Infinileap", "Spirit Leap") ?: false
use itemid

2024-07-17 15:18 UTC, freebonsai commented on odin/src/main/kotlin/me/odin/features/impl/floor7/p3/ArrowsDevice.kt
> +        if(!isDeviceComplete && activeArmorStand?.name == ACTIVE_DEVICE_STRING)  {
formatting

2024-07-17 15:18 UTC, freebonsai commented on odin/src/main/kotlin/me/odin/features/impl/floor7/p3/ArrowsDevice.kt
> +    private fun isPlayerInRoom(): Boolean {
make both of these val getters, just cleaner

2024-07-17 15:18 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/floor7/p3/ArrowsDevice.kt
> +
do all the same stuff as i commented in legit version

2024-07-17 15:18 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/floor7/p3/ArrowsDevice.kt
> +    private val classes = listOf(DungeonClass.Archer, DungeonClass.Mage, DungeonClass.Berserk, DungeonClass.Healer, DungeonClass.Tank)
DungeonClass.entries?

2024-07-17 15:18 UTC, freebonsai commented on odinclient/src/main/kotlin/me/odinclient/features/impl/floor7/p3/ArrowsDevice.kt
> +    private const val ACTIVE_DEVICE_STRING = "\u00A7aDevice"
cant you just write §  ?

2024-07-17 16:14 UTC, viandoxdev commented
> Just small stuff, do you have a recent video of how it works with everything? Tell me when you have fixed my comments and I will look over again and merge.

The demo above is fairly recent the only differences with now are a few debug mod messages i removed and some formatting.

2024-07-18 15:19 UTC, freebonsai commented
make a drop down menu for the settings so its more obvious what are settings for auto, look in PuzzleSolvers.kt for help

2024-07-18 15:20 UTC, freebonsai commented on odin/src/main/kotlin/me/odin/features/impl/floor7/p3/ArrowsDevice.kt
> +            // Cast is safe since we won't return an entity that isn't an armor stand
you can just filterIsInstance<EntityArmorStand>() before your find and you will not need to cast

2024-07-18 15:26 UTC, freebonsai requested changes
Idk fix the one thing i commented about drop down and filterIsInstance and i will merge

2024-07-22 07:08 UTC, viandoxdev commented
Is that good yet ? @freebonsai

2024-07-29 20:51 UTC, freebonsai approved these changes

2024-07-29 20:53 UTC, freebonsai commented
Can you resolve all conflicts between yours and main branch and ping me in discord when you are done, i will merge it after.

2024-07-31 14:13 UTC, merged